- name: Instalar y configurar MySQL en Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Instalar dependencias de Python para MySQL
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Instalar MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Asegurar que MySQL esté corriendo
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Crear base de datos
      mysql_db:
        name: appdb
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Crear usuario de MySQL
      mysql_user:
        name: appuser
        password: "app_password"
        priv: 'appdb.*:ALL'
        host: '%'
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock